service: sentry-node

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    SENTRY_ENVIRONMENT: ${opt:stage, self:provider.stage} # Optional
    # SENTRY_RELEASE: ${git:sha1} # Optional, example needs serverless-plugin-git-variables 
    SENTRY_TRACES_SAMPLE_RATE: '1.0'
    SENTRY_DSN: ${env:SENTRY_DSN}
    NODE_OPTIONS: '-r @sentry/serverless/dist/awslambda-auto'

custom:
  layers:
    - arn:aws:lambda:${self:provider.region}:943013980633:layer:SentryNodeServerlessSDK:26

functions:
  hello:
    handler: handler.hello
    layers: ${self:custom.layers}

